from . import metabase_config
from . import sync_log
from . import res_partner_student
from . import student_mass_update
from . import res_partner_lead_stage
from . import res_partner_parent
from . import res_partner_subscription
from . import res_partner_attendance
from . import res_partner_payment_receive
