from . import metabase_config
from . import sync_log
from . import res_partner_student
from . import res_partner_lead_stage
from . import res_partner_student_phase
from . import res_partner_parent
from . import res_partner_subscription
from . import res_partner_attendance
from . import res_partner_payment_receive
from . import res_partner_payment_slot_selection
from . import res_partner_payment_paid_access
from . import student_mass_update
